### ISSUE TITLE
 Next: FOUC when loading

### ISSUE THREAD

**Issue by bfabio** [italia/designers.italia.it#472]
Looks like the right fonts are applied when the page is loaded, example hitting CTRL+R in a loop:

[Screencast from 2022-11-25 15-48-14.webm](https://user-images.githubusercontent.com/788293/204008953-245c1be3-cbc3-4a13-9ade-e957de0333de.webm)

Tested on:
* Chrome Desktop
* Chromium
* Firefox Desktop

**Comment by Fupete** [comment]
Tx @bfabio, I just added the right metadata to this. Backlog for Monday 👍 folks.

**Comment by gpeirolo** [comment]
@Fupete it has to do with the BI font loader. The fonts styles are witten in the head tag by a script esxecuted when te page is loaded. Gatsby pages are seemingly not caching something beacuse regular html pages built with BI work fine.
We'll look into this ASAP.

**Comment by gpeirolo** [comment]
@Fupete @astagi together with @marsanwedoo we made some tests. Here are our findings:
- the flash (and the occasional blank) is more visibile on the build because all resources are not cachable as served by vercel (timeout is always 0)
- the FOUC is due to the font script not being launched directly but being launched during the import of some other BI component (esm problem, ask @marsanwedoo for more info about that)
- theoretically it's launched at template building but probably not soon enough

Right now, assuming changes are first made to BI anyway, the solution could be:
- quick fix: using CSS to import the fonts (not goot for performance though)
- using this plugin https://www.gatsbyjs.com/plugins/gatsby-plugin-web-font-loader/ which seems to have support for local fonts

**Comment by Fupete** [comment]
Ooook. 

Maybe @bfabio can help/enlighten us about Vercel timeout. 

I let @astagi evaluate, I have just read this on Gatsby documentation about preload fonts https://www.gatsbyjs.com/docs/how-to/styling/using-local-fonts/#preload-your-fonts, can help?
