### ISSUE TITLE
Add linting to the pipeline

### ISSUE THREAD

**Issue by bfabio** [italia/designers.italia.it#630]
We need to lint and uniform the code style, and enforce that in the development process by adding eslint (end possibily other linters) to the CI.

**Comment by Lorenzo-Pappalardo** [comment]
Hi! 😄 
I have configured ESLint and Prettier for linting and formatting the code base and opened this PR #678.
It is marked as draft because I have just provided the basic configurations for the tools and, since it is important to set the wanted linting and formatting preferences before proceeding with applying them to the code, I will wait for your feedback.
Let me know what you think 😉

**Comment by bfabio** [comment]
Depends on #848

**Comment by bfabio** [comment]
Reopening, see #904.
